- name: se_s
  become: true
  hosts: all
  remote_user: eadm

  tasks:

    - name: Creates directory
      file:
        path: /data/elasticsearch
        state: directory
        owner: 1000
        group: 1000
        mode: 0700
    
    - name: Creates directory
      file:
        path: /data/elasticsearch/log
        state: directory
        owner: 1000
        group: 1000
        mode: 0700 
    
    - name: Creates directory
      file:
        path: /home/eadm/elasticsearch
        state: directory
        owner: 1000
        group: 1000
        mode: 0700

    - name: create compose
      copy:
        content: "
        version: '2.2'\n
        services:\n
        \ \ {{ ansible_hostname }}:\n
        \ \ \ \ image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1\n
        \ \ \ \ container_name: {{ ansible_hostname }}\n
        \ \ \ \ environment:\n
        \ \ \ \ \ - node.name={{ ansible_hostname }}\n
        \ \ \ \ \ - ELASTIC_PASSWORD= limon\n
        \ \ \ \ \ - cluster.name=es--cluster\n
        \ \ \ \ \ - network.publish_host={{ ansible_host }}\n
        \ \ \ \ \ - cluster.initial_master_nodes=192.168.1.41,192.168.1.42,192.168.1.43\n
        \ \ \ \ \ - discovery.seed_hosts=172.18.26.44,172.18.26.45,172.18.26.46,172.18.26.47,172.18.26.48,172.18.26.49,172.18.26.50,172.18.26.51,172.18.26.52,172.18.26.53,172.18.26.54,172.18.26.55,172.18.26.56,172.18.26.57,172.18.26.58,172.18.26.59,172.18.26.60,172.18.26.61,172.18.26.62,172.18.26.63,172.18.26.64,172.18.26.65,172.18.26.66,172.18.26.67,172.18.26.68,172.18.26.69,172.18.26.70,172.18.26.71,172.18.26.72,172.18.26.73,172.18.26.74,172.18.26.75,172.18.26.76,172.18.26.77,172.18.26.78,172.18.26.79,172.18.26.80,172.18.26.81,172.18.26.82,172.18.26.83,172.18.26.84,172.18.26.85,172.18.26.86,172.18.26.87,172.18.26.88,172.18.26.89,172.18.26.90,172.18.26.91,172.18.26.92,172.18.26.93\n
        \ \ \ \ \ - bootstrap.memory_lock=true\n
        \ \ \ \ \ - network.host=0.0.0.0\n
        \ \ \ \ \ - node.master=false\n
        \ \ \ \ \ - node.data=true\n
        \ \ \ \ \ - ES_JAVA_OPTS=-Xms16g -Xmx16g\n
        \ \ \ \ ulimits:\n
        \ \ \ \ \ \ memlock:\n
        \ \ \ \ \ \ \ soft: -1\n
        \ \ \ \ \ \ \ hard: -1\n
        \ \ \ \ volumes:\n
        \ \ \ \ \ - /data/elasticsearch:/usr/share/elasticsearch/data\n
        \ \ \ \ \ - /data/log/elasticsearch:/var/log/elasticsearch\n
        \ \ \ \ ports:\n
        \ \ \ \ \ - 9200:9200\n
        \ \ \ \ \ - 9300:9300\n"
        dest: "/home/eadm/elasticsearch/docker-compose.yml"
